WITH ods_products AS 
(
    SELECT 
    *,
      ROW_NUMBER() OVER (PARTITION BY PRODUCT_ID ORDER BY updated_at DESC NULLS LAST) AS rnk
    FROM {{ref('ods_products')}}
)

SELECT 
    {{ dbt_utils.generate_surrogate_key(['PRODUCT_ID','PRODUCT_CATEGORY_NAME']) }} as PRODUCT_PK,
    PRODUCT_ID,
    PRODUCT_CATEGORY_NAME,
    CASE 
    WHEN PRODUCT_NAME_LENGHT IS NULL 
    THEN 0 
    ELSE PRODUCT_NAME_LENGHT 
    END as PRODUCT_NAME_LENGHT, 
    CASE 
    WHEN PRODUCT_PHOTOS_QTY IS NULL 
    THEN 0 
    ELSE PRODUCT_PHOTOS_QTY 
    END as PRODUCT_PHOTOS_QTY,
    CASE 
    WHEN PRODUCT_WEIGHT_G IS NULL 
    THEN 0 
    ELSE PRODUCT_WEIGHT_G 
    END as PRODUCT_WEIGHT_G,
    CASE 
    WHEN PRODUCT_LENGTH_CM IS NULL 
    THEN 0 
    ELSE PRODUCT_LENGTH_CM 
    END as PRODUCT_LENGTH_CM,
    CASE 
    WHEN PRODUCT_HEIGHT_CM IS NULL 
    THEN 0 
    ELSE PRODUCT_HEIGHT_CM 
    END as PRODUCT_HEIGHT_CM,
    CASE 
    WHEN PRODUCT_WIDTH_CM IS NULL 
    THEN 0 
    ELSE PRODUCT_WIDTH_CM 
    END as PRODUCT_WIDTH_CM,
FROM ods_products
WHERE rnk = 1