USE DATABASE OLIST_DB;
USE SCHEMA OLIST_DB.RAW;

-- customers

CREATE OR REPLACE STREAM stg_customers_stream
ON TABLE RAW.customers_raw
APPEND_ONLY = FALSE;

CREATE OR REPLACE TASK refresh_stg_customers
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 19 17 * * * UTC'
AS 
MERGE INTO STAGING.stg_customers AS tgt
USING (
    SELECT 
        customer_id,
        customer_unique_id,
        customer_zip_code_prefix,
        customer_city,
        customer_state,
        METADATA$ACTION,
        METADATA$ISUPDATE
    FROM stg_customers_stream
) AS src
ON tgt.customer_id = src.customer_id

WHEN MATCHED AND src.METADATA$ACTION = 'DELETE' THEN
    DELETE

WHEN MATCHED AND src.METADATA$ACTION = 'INSERT' THEN
    UPDATE SET
        tgt.customer_unique_id = src.customer_unique_id,
        tgt.customer_zip_code_prefix = src.customer_zip_code_prefix,
        tgt.customer_city = src.customer_city,
        tgt.customer_state = src.customer_state,
        tgt.updated_at = CURRENT_TIMESTAMP()

WHEN NOT MATCHED AND src.METADATA$ACTION = 'INSERT' THEN
    INSERT (
        customer_id,
        customer_unique_id,
        customer_zip_code_prefix,
        customer_city,
        customer_state,
        created_at,
        updated_at
    )
    VALUES (
        src.customer_id,
        src.customer_unique_id,
        src.customer_zip_code_prefix,
        src.customer_city,
        src.customer_state,
        CURRENT_TIMESTAMP(),
        CURRENT_TIMESTAMP()
    );


-- geolocation 

CREATE OR REPLACE STREAM stg_geolocation_stream
ON TABLE RAW.geolocation_raw
APPEND_ONLY = FALSE;

CREATE OR REPLACE TASK refresh_stg_geolocation
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 19 17 * * * UTC'
AS 
MERGE INTO STAGING.STG_GEOLOCATION AS tgt 
USING( 
    SELECT * FROM stg_geolocation_stream
) as src 
on src.GEOLOCATION_ZIP_CODE_PREFIX = tgt.GEOLOCATION_ZIP_CODE_PREFIX

WHEN MATCHED AND src.METADATA$ACTION = 'DELETE' THEN 
DELETE 

WHEN MATCHED AND src.METADATA$ACTION = 'INSERT' THEN
 UPDATE SET
  tgt.GEOLOCATION_ZIP_CODE_PREFIX = src.GEOLOCATION_ZIP_CODE_PREFIX , 
  tgt.GEOLOCATION_LAT = src.GEOLOCATION_LAT, 
  tgt.GEOLOCATION_LNG = src.GEOLOCATION_LAT, 
  tgt.GEOLOCATION_CITY = src.GEOLOCATION_CITY, 
  tgt.GEOLOCATION_STATE = src.GEOLOCATION_STATE,  
  tgt.UPDATED_AT = CURRENT_TIMESTAMP(), 
 tgt.CREATED_AT= CURRENT_TIMESTAMP() 

WHEN NOT MATCHED AND src.METADATA$ACTION = 'INSERT' THEN
 INSERT(
  tgt.GEOLOCATION_ZIP_CODE_PREFIX , 
  tgt.GEOLOCATION_LAT , 
  tgt.GEOLOCATION_LNG , 
  tgt.GEOLOCATION_CITY , 
  tgt.GEOLOCATION_STATE ,  
  tgt.UPDATED_AT ,
  tgt.CREATED_AT
 )
 VALUES 
 (
 src.GEOLOCATION_ZIP_CODE_PREFIX, 
 src.GEOLOCATION_LAT,
 src.GEOLOCATION_LAT,
 src.GEOLOCATION_CITY,
 CURRENT_TIMESTAMP(),
 CURRENT_TIMESTAMP()
 )
;


-- order_items 

CREATE OR REPLACE STREAM stg_order_items_stream
ON TABLE RAW.orders_items_raw
APPEND_ONLY = FALSE;

CREATE OR REPLACE TASK refresh_stg_order_items
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 19 17 * * * UTC'
AS 
MERGE INTO STAGING.stg_order_items AS tgt
USING (
    SELECT * FROM stg_order_items_stream
) AS src
ON tgt.ORDER_ITEM_ID = src.ORDER_ITEM_ID

WHEN MATCHED AND src.METADATA$ACTION = 'DELETE' THEN
    DELETE

WHEN MATCHED AND src.METADATA$ACTION = 'INSERT' THEN
    UPDATE SET
        ORDER_ID = src.ORDER_ID,
        PRODUCT_ID = src.PRODUCT_ID,
        SELLER_ID = src.SELLER_ID,
        SHIPPING_LIMIT_DATE = src.SHIPPING_LIMIT_DATE,
        PRICE = src.PRICE,
        FREIGHT_VALUE = src.FREIGHT_VALUE,
        UPDATED_AT = CURRENT_TIMESTAMP()

WHEN NOT MATCHED AND src.METADATA$ACTION = 'INSERT' THEN
    INSERT (
        ORDER_ID,
        ORDER_ITEM_ID,
        PRODUCT_ID,
        SELLER_ID,
        SHIPPING_LIMIT_DATE,
        PRICE,
        FREIGHT_VALUE,
        CREATED_AT,
        UPDATED_AT
    )
    VALUES (
        src.ORDER_ID,
        src.ORDER_ITEM_ID,
        src.PRODUCT_ID,
        src.SELLER_ID,
        src.SHIPPING_LIMIT_DATE,
        src.PRICE,
        src.FREIGHT_VALUE,
        CURRENT_TIMESTAMP(),
        CURRENT_TIMESTAMP()
    );


-- order_payments

CREATE OR REPLACE STREAM stg_order_payments_stream
ON TABLE RAW.orders_payments_raw
APPEND_ONLY = FALSE;

CREATE OR REPLACE TASK refresh_stg_order_payments
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 19 17 * * * UTC'
AS 
MERGE INTO STAGING.stg_order_payments AS tgt
USING (
    SELECT * FROM stg_order_payments_stream
) AS SRC 
ON SRC.ORDER_ID = tgt.ORDER_ID

WHEN MATCHED AND SRC.METADATA$ACTION='DELETE' THEN 
DELETE 

WHEN MATCHED AND SRC.METADATA$ACTION='INSERT' THEN 
UPDATE SET 
tgt.PAYMENT_SEQUENTIAL= src.PAYMENT_SEQUENTIAL,
tgt.PAYMENT_TYPE= src.PAYMENT_TYPE,
tgt.PAYMENT_INSTALLMENTS= src.PAYMENT_TYPE,
tgt.PAYMENT_VALUE= src.PAYMENT_TYPE,
tgt.UPDATED_AT= CURRENT_TIMESTAMP()

WHEN NOT MATCHED AND SRC.METADATA$ACTION='INSERT' THEN 
INSERT( 
    ORDER_ID,
PAYMENT_SEQUENTIAL,
PAYMENT_TYPE,
PAYMENT_INSTALLMENTS,
PAYMENT_VALUE,
CREATED_AT,
UPDATED_AT
)
VALUES(
src.ORDER_ID,
src.PAYMENT_SEQUENTIAL,
src.PAYMENT_TYPE,
src.PAYMENT_INSTALLMENTS,
src.PAYMENT_VALUE,
CURRENT_TIMESTAMP(),
CURRENT_TIMESTAMP()
);

--order_reviews

CREATE OR REPLACE STREAM stg_order_reviews_stream
ON TABLE RAW.orders_reviews_raw
APPEND_ONLY = FALSE;

CREATE OR REPLACE TASK refresh_stg_order_reviews
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 19 17 * * * UTC'
AS 
MERGE INTO STAGING.stg_order_review AS tgt 
USING (
    SELECT * FROM stg_order_reviews_stream
) as SRC
ON SRC.REVIEW_ID and tgt.REVIEW_ID
AND SRC.ORDER_ID and tgt.ORDER_ID

WHEN MATCHED AND SRC.METADATA$ACTION='DELETE' THEN 
DELETE 

WHEN MATCHED AND SRC.METADATA$ACTION='INSERT' THEN 
UPDATE SET 
tgt.REVIEW_ID= src.REVIEW_ID ,
tgt.ORDER_ID= src.ORDER_ID ,
tgt.REVIEW_SCORE= src.REVIEW_SCORE ,
tgt.REVIEW_COMMENT_TITLE= src.REVIEW_COMMENT_TITLE ,
tgt.REVIEW_COMMENT_MESSAGE= src.REVIEW_COMMENT_MESSAGE ,
tgt.REVIEW_CREATION_DATE= src.REVIEW_CREATION_DATE ,
tgt.REVIEW_ANSWER_TIMESTAMP= src.REVIEW_CREATION_DATE ,
tgt.UPDATED_AT= src.UPDATED_AT 

WHEN NOT MATCHED AND SRC.METADATA$ACTION='INSERT' THEN 
INSERT (
REVIEW_ID,
ORDER_ID,
REVIEW_SCORE,
REVIEW_COMMENT_TITLE,
REVIEW_COMMENT_MESSAGE,
REVIEW_CREATION_DATE,
REVIEW_ANSWER_TIMESTAMP,
CREATED_AT,
UPDATED_AT
)
VALUES (
src.REVIEW_ID,
src.ORDER_ID,
src.REVIEW_SCORE,
src.REVIEW_COMMENT_TITLE,
src.REVIEW_COMMENT_MESSAGE,
src.REVIEW_CREATION_DATE,
src.REVIEW_ANSWER_TIMESTAMP,
CURRENT_TIMESTAMP(),
CURRENT_TIMESTAMP()
);

--orders 

CREATE OR REPLACE STREAM stg_orders_stream
ON TABLE RAW.orders_raw
APPEND_ONLY = FALSE;

CREATE OR REPLACE TASK refresh_stg_orders
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 19 17 * * * UTC'
AS 
MERGE INTO STAGING.stg_orders AS TGT 
USING (
    SELECT * FROM stg_orders_stream
) AS SRC 
ON SRC.ORDER_ID = TGT.ORDER_ID

WHEN MATCHED AND SRC.METADATA$ACTION = 'DELETE' THEN 
DELETE 

WHEN MATCHED AND SRC.METADATA$ACTION = 'INSERT' THEN
UPDATE SET 
tgt.ORDER_ID= src.ORDER_ID ,
tgt.CUSTOMER_ID= src.CUSTOMER_ID ,
tgt.ORDER_STATUS= src.ORDER_STATUS ,
tgt.ORDER_PURCHASE_TIMESTAMP= src.ORDER_PURCHASE_TIMESTAMP ,
tgt.ORDER_APPROVED_AT= src.ORDER_APPROVED_AT ,
tgt.ORDER_DELIVERED_CARRIER= src.ORDER_DELIVERED_CARRIER ,
tgt.ORDER_DELIVERED_CUSTOMER_DATE= src.ORDER_DELIVERED_CUSTOMER_DATE ,
tgt.ORDER_ESTIMATED_DELIVERY_DATE= src.ORDER_ESTIMATED_DELIVERY_DATE ,
tgt.UPDATED_AT= CURRENT_TIMESTAMP()

WHEN NOT MATCHED AND SRC.METADATA$ACTION = 'INSERT' THEN
INSERT
(
ORDER_ID,
CUSTOMER_ID,
ORDER_STATUS,
ORDER_PURCHASE_TIMESTAMP,
ORDER_APPROVED_AT,
ORDER_DELIVERED_CARRIER,
ORDER_DELIVERED_CUSTOMER_DATE,
ORDER_ESTIMATED_DELIVERY_DATE,
CREATED_AT,
UPDATED_AT

)
VALUES
(
src.ORDER_ID,
src.CUSTOMER_ID,
src.ORDER_STATUS,
src.ORDER_PURCHASE_TIMESTAMP,
src.ORDER_APPROVED_AT,
src.ORDER_DELIVERED_CARRIER,
src.ORDER_DELIVERED_CUSTOMER_DATE,
src.ORDER_ESTIMATED_DELIVERY_DATE,
CURRENT_TIMESTAMP(),
CURRENT_TIMESTAMP()
);

-- products

CREATE OR REPLACE STREAM stg_products_stream
ON TABLE RAW.products_raw
APPEND_ONLY = FALSE;

CREATE OR REPLACE TASK refresh_stg_products
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 19 17 * * * UTC'
AS 
MERGE INTO STAGING.stg_products as TGT 
USING 
(
select * from stg_products_stream) as SRC 
ON TGT.PRODUCT_ID = SRC.PRODUCT_ID

WHEN MATCHED AND SRC.METADATA$ACTION = 'DELETE' THEN 
DELETE 

WHEN MATCHED AND SRC.METADATA$ACTION = 'INSERT' THEN 
UPDATE SET 
tgt.PRODUCT_ID= src.PRODUCT_ID ,
tgt.PRODUCT_CATEGORY_NAME= src.PRODUCT_CATEGORY_NAME ,
tgt.PRODUCT_NAME_LENGHT= src.PRODUCT_NAME_LENGHT ,
tgt.PRODUCT_DESCRIPTION_LENGHT= src.PRODUCT_DESCRIPTION_LENGHT ,
tgt.PRODUCT_PHOTOS_QTY= src.PRODUCT_PHOTOS_QTY ,
tgt.PRODUCT_WEIGHT_G= src.PRODUCT_WEIGHT_G ,
tgt.PRODUCT_LENGTH_CM= src.PRODUCT_LENGTH_CM ,
tgt.PRODUCT_HEIGHT_CM= src.PRODUCT_HEIGHT_CM ,
tgt.PRODUCT_WIDTH_CM= src.PRODUCT_WIDTH_CM ,
tgt.UPDATED_AT= CURRENT_TIMESTAMP()

WHEN NOT MATCHED AND SRC.METADATA$ACTION = 'INSERT' THEN 
INSERT(
PRODUCT_ID, PRODUCT_CATEGORY_NAME, PRODUCT_NAME_LENGHT, PRODUCT_DESCRIPTION_LENGHT, PRODUCT_PHOTOS_QTY, PRODUCT_WEIGHT_G, PRODUCT_LENGTH_CM, PRODUCT_HEIGHT_CM, PRODUCT_WIDTH_CM, CREATED_AT, UPDATED_AT
)
VALUES 
(
src.PRODUCT_ID,
src.PRODUCT_CATEGORY_NAME,
src.PRODUCT_NAME_LENGHT,
src.PRODUCT_DESCRIPTION_LENGHT,
src.PRODUCT_PHOTOS_QTY,
src.PRODUCT_WEIGHT_G,
src.PRODUCT_LENGTH_CM,
src.PRODUCT_HEIGHT_CM,
src.PRODUCT_WIDTH_CM,
CURRENT_TIMESTAMP(),
CURRENT_TIMESTAMP()
);

--sellers

CREATE OR REPLACE STREAM stg_sellers_stream
ON TABLE RAW.seller_raw
APPEND_ONLY = FALSE;

CREATE OR REPLACE TASK refresh_stg_sellers
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 19 17 * * * UTC'
AS 
MERGE INTO STAGING.stg_sellers AS tgt
USING 
(SELECT * FROM stg_sellers_stream ) AS src
ON src.SELLER_ID = tgt.SELLER_ID 

WHEN MATCHED AND src.METADATA$ACTION ='DELETE' THEN 
DELETE

WHEN MATCHED AND src.METADATA$ACTION ='INSERT' THEN 
UPDATE SET 
tgt.SELLER_ID= src.SELLER_ID ,
tgt.SELLER_ZIP_CODE_PREFIX= src.SELLER_ZIP_CODE_PREFIX ,
tgt.SELLER_CITY= src.SELLER_CITY ,
tgt.SELLER_STATE= src.SELLER_STATE ,
tgt.UPDATED_AT= CURRENT_TIMESTAMP()

WHEN NOT MATCHED AND src.METADATA$ACTION ='INSERT' THEN 
INSERT(
SELLER_ID, SELLER_ZIP_CODE_PREFIX, SELLER_CITY, SELLER_STATE, CREATED_AT, UPDATED_AT
)
VALUES
(
src.SELLER_ID,
src.SELLER_ZIP_CODE_PREFIX,
src.SELLER_CITY,
src.SELLER_STATE,
CURRENT_TIMESTAMP(),
CURRENT_TIMESTAMP()
);

--product_category_name_translation

CREATE OR REPLACE STREAM stg_product_category_name_translation_stream
ON TABLE RAW.product_category_name_translation_raw
APPEND_ONLY = FALSE;


CREATE OR REPLACE TASK refresh_stg_product_category_name_translation
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 19 17 * * * UTC'
AS 
MERGE INTO STAGING.stg_product_category_name_translation AS tgt
USING(
SELECT * FROM stg_product_category_name_translation_stream
) AS src
ON tgt.PRODUCT_CATEGORY_NAME = src.PRODUCT_CATEGORY_NAME

WHEN MATCHED AND src.METADATA$ACTION='DELETE' THEN 
DELETE 

WHEN MATCHED AND src.METADATA$ACTION='INSERT' THEN 
UPDATE SET 
tgt.PRODUCT_CATEGORY_NAME= src.PRODUCT_CATEGORY_NAME ,
tgt.PRODUCT_CATEGORY_NAME_ENGLISH= src.PRODUCT_CATEGORY_NAME ,
tgt.UPDATED_AT= CURRENT_TIMESTAMP() 

WHEN NOT MATCHED AND src.METADATA$ACTION='INSERT' THEN 
INSERT 
(
PRODUCT_CATEGORY_NAME, PRODUCT_CATEGORY_NAME_ENGLISH, CREATED_AT, UPDATED_AT
)
VALUES 
(
src.PRODUCT_CATEGORY_NAME ,
src.PRODUCT_CATEGORY_NAME ,
CURRENT_TIMESTAMP() ,
CURRENT_TIMESTAMP()
);




ALTER TASK refresh_stg_customers RESUME;
ALTER TASK refresh_stg_geolocation RESUME;
ALTER TASK refresh_stg_orders RESUME;
ALTER TASK refresh_stg_order_items RESUME;
ALTER TASK refresh_stg_order_payments RESUME;
ALTER TASK refresh_stg_order_reviews RESUME;
ALTER TASK refresh_stg_products RESUME;
ALTER TASK refresh_stg_sellers RESUME;
ALTER TASK refresh_stg_product_category_name_translation RESUME;