USE ROLE ACCOUNTADMIN;

CREATE USER IF NOT EXISTS OLIST_USER
  PASSWORD='olist1234'
  LOGIN_NAME='olist'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE=TRANSFORM
  DEFAULT_NAMESPACE='OLIST_DB.RAW'
  COMMENT='Olist user used for data transformation';
ALTER USER OLIST_USER SET TYPE = LEGACY_SERVICE;
GRANT ROLE OLIST_TRANSFORM to USER OLIST_USER;
