USE DATABASE OLIST_DB;
USE SCHEMA OLIST_DB.RAW;

CREATE OR REPLACE PIPE orders_raw_pipe
AUTO_INGEST = TRUE
AS 
COPY INTO RAW.orders_raw
FROM @olist_stage
FILE_FORMAT = (TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1 error_on_column_count_mismatch=false)
ON_ERROR ='CONTINUE';

CREATE OR REPLACE PIPE customers_raw_pipe
AUTO_INGEST = TRUE
AS 
COPY INTO RAW.customers_raw
FROM @olist_stage
FILE_FORMAT = (TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1 error_on_column_count_mismatch=false)
ON_ERROR ='CONTINUE';

CREATE OR REPLACE PIPE geolocation_raw_pipe
AUTO_INGEST = TRUE
AS 
COPY INTO RAW.geolocation_raw
FROM @olist_stage
FILE_FORMAT = (TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1 error_on_column_count_mismatch=false)
ON_ERROR ='CONTINUE';

CREATE OR REPLACE PIPE ORDERS_ITEMS_raw_pipe
AUTO_INGEST = TRUE
AS 
COPY INTO RAW.ORDERS_ITEMS_raw
FROM @olist_stage
FILE_FORMAT = (TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1 error_on_column_count_mismatch=false)
ON_ERROR ='CONTINUE';

CREATE OR REPLACE PIPE ORDERS_PAYMENTS_raw_pipe
AUTO_INGEST = TRUE
AS 
COPY INTO RAW.ORDERS_PAYMENTS_raw
FROM @olist_stage
FILE_FORMAT = (TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1 error_on_column_count_mismatch=false)
ON_ERROR ='CONTINUE';

CREATE OR REPLACE PIPE ORDERS_REVIEWS_raw_pipe
AUTO_INGEST = TRUE
AS 
COPY INTO RAW.ORDERS_REVIEWS_raw
FROM @olist_stage
FILE_FORMAT = (TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1 error_on_column_count_mismatch=false)
ON_ERROR ='CONTINUE';

CREATE OR REPLACE PIPE PRODUCTS_raw_pipe
AUTO_INGEST = TRUE
AS 
COPY INTO RAW.PRODUCTS_raw
FROM @olist_stage
FILE_FORMAT = (TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1 error_on_column_count_mismatch=false)
ON_ERROR ='CONTINUE';

CREATE OR REPLACE PIPE product_category_name_translation_raw_pipe
AUTO_INGEST = TRUE
AS 
COPY INTO RAW.product_category_name_translation_raw
FROM @olist_stage
FILE_FORMAT = (TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1 error_on_column_count_mismatch=false)
ON_ERROR ='CONTINUE';

CREATE OR REPLACE PIPE SELLER_pipe
AUTO_INGEST = TRUE
AS 
COPY INTO RAW.SELLER_raw
FROM @olist_stage
FILE_FORMAT = (TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1 error_on_column_count_mismatch=false)
ON_ERROR ='CONTINUE';