USE DATABASE OLIST_DB;
USE SCHEMA olist_db.staging;

CREATE OR REPLACE TABLE STAGING.stg_customers AS 
SELECT 
    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    COALESCE(CUSTOMER_ZIP_CODE_PREFIX, 0) AS CUSTOMER_ZIP_CODE_PREFIX,
    UPPER(TRIM(CUSTOMER_CITY)) AS CUSTOMER_CITY,
    UPPER(TRIM(CUSTOMER_STATE)) AS CUSTOMER_STATE,
    CURRENT_TIMESTAMP() AS created_at,
    CURRENT_TIMESTAMP() AS updated_at
FROM RAW.customers_raw
WHERE CUSTOMER_ID IS NOT NULL ;

CREATE OR REPLACE TABLE STAGING.stg_geolocation AS
SELECT 
    GEOLOCATION_ZIP_CODE_PREFIX, 
    GEOLOCATION_LAT, 
    COALESCE(GEOLOCATION_LNG, 0) AS GEOLOCATION_LNG ,
    UPPER(TRIM(GEOLOCATION_CITY)) AS GEOLOCATION_CITY, 
    UPPER(TRIM(GEOLOCATION_STATE)) AS GEOLOCATION_STATE, 
    CURRENT_TIMESTAMP() AS CREATED_AT, 
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM RAW.geolocation_raw
WHERE GEOLOCATION_ZIP_CODE_PREFIX is not null;

CREATE OR REPLACE TABLE STAGING.stg_orders_items AS
SELECT
    ORDER_ID, 
    ORDER_ITEM_ID, 
    PRODUCT_ID, 
    SELLER_ID, 
    SHIPPING_LIMIT_DATE, 
    PRICE, 
    FREIGHT_VALUE, 
    CURRENT_TIMESTAMP() AS CREATED_AT, 
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM RAW.ORDERS_ITEMS_RAW
WHERE ORDER_ID IS NOT NULL ;

CREATE OR REPLACE TABLE STAGING.stg_orders_payments AS
SELECT 
    ORDER_ID, 
    PAYMENT_SEQUENTIAL, 
    COALESCE(PAYMENT_TYPE,'UNKNOWN') AS PAYMENT_TYPE, 
    COALESCE(PAYMENT_INSTALLMENTS,'UNKNOWN') AS  PAYMENT_INSTALLMENTS,
    PAYMENT_VALUE, 
    CURRENT_TIMESTAMP() AS CREATED_AT, 
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM RAW.ORDERS_PAYMENTS_RAW
WHERE ORDER_ID IS NOT NULL ;

CREATE OR REPLACE TABLE STAGING.stg_orders AS
SELECT
    ORDER_ID, 
    CUSTOMER_ID, 
    COALESCE(ORDER_STATUS,'UNKOWN') AS  ORDER_STATUS,
    ORDER_PURCHASE_TIMESTAMP, 
    ORDER_APPROVED_AT, 
    ORDER_DELIVERED_CARRIER, 
    CAST(ORDER_DELIVERED_CUSTOMER_DATE AS TIMESTAMP_NTZ) AS ORDER_DELIVERED_CUSTOMER_DATE, 
    CAST(ORDER_ESTIMATED_DELIVERY_DATE AS TIMESTAMP_NTZ) AS ORDER_ESTIMATED_DELIVERY_DATE, 
    CURRENT_TIMESTAMP() AS CREATED_AT, 
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM raw.orders_raw
WHERE ORDER_ID IS NOT NULL AND CUSTOMER_ID IS NOT NULL ;

CREATE OR REPLACE TABLE STAGING.stg_orders_reviews AS
SELECT 
    REVIEW_ID, 
    ORDER_ID, 
    REVIEW_SCORE, 
    REVIEW_COMMENT_TITLE, 
    REVIEW_COMMENT_MESSAGE, 
    cast(REVIEW_CREATION_DATE as timestamp) as REVIEW_CREATION_DATE, 
    cast(REVIEW_ANSWER_TIMESTAMP as timestamp) as REVIEW_ANSWER_TIMESTAMP, 
    CURRENT_TIMESTAMP() AS CREATED_AT, 
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM RAW.ORDERS_REVIEWS_RAW
WHERE REVIEW_ID is not null and ORDER_ID is not null ;

CREATE OR REPLACE TABLE STAGING.stg_products AS
SELECT
    PRODUCT_ID, 
    coalesce(PRODUCT_CATEGORY_NAME,'UNKNOWN') as PRODUCT_CATEGORY_NAME, 
    cast(PRODUCT_NAME_LENGHT as number) as PRODUCT_NAME_LENGHT, 
    cast(PRODUCT_DESCRIPTION_LENGHT as number) as PRODUCT_DESCRIPTION_LENGHT, 
    cast(PRODUCT_PHOTOS_QTY as number) as PRODUCT_PHOTOS_QTY, 
    cast(PRODUCT_WEIGHT_G as number) as PRODUCT_WEIGHT_G, 
    cast(PRODUCT_LENGTH_CM as number) as PRODUCT_LENGTH_CM, 
    cast(PRODUCT_HEIGHT_CM as number) as PRODUCT_HEIGHT_CM, 
    cast(PRODUCT_WIDTH_CM as number) as PRODUCT_WIDTH_CM, 
    CURRENT_TIMESTAMP() AS CREATED_AT, 
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM raw.products_raw
WHERE PRODUCT_ID is not null ;

CREATE OR REPLACE TABLE STAGING.stg_product_category_name_translation AS 
SELECT 
    coalesce(PRODUCT_CATEGORY_NAME,'UNKNOWN') AS  PRODUCT_CATEGORY_NAME,
    coalesce(PRODUCT_CATEGORY_NAME_ENGLISH,'UNKNOWN') AS  PRODUCT_CATEGORY_NAME_ENGLISH,
    CURRENT_TIMESTAMP() AS CREATED_AT, 
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM RAW.PRODUCT_CATEGORY_NAME_TRANSLATION_RAW;

CREATE OR REPLACE TABLE STAGING.stg_seller AS 
SELECT 
    SELLER_ID, 
    SELLER_ZIP_CODE_PREFIX, 
    SELLER_CITY, 
    SELLER_STATE, 
    CURRENT_TIMESTAMP() AS CREATED_AT, 
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM RAW.SELLER_RAW 
WHERE SELLER_ID IS NOT NULL;