USE DATABASE OLIST_DB;

CREATE OR REPLACE ROLE ENGINEER;
CREATE OR REPLACE ROLE ANALYST;
CREATE OR REPLACE ROLE REPORTER;

GRANT USAGE ON DATABASE OLIST_DB TO ROLE ENGINEER;
GRANT USAGE ON SCHEMA RAW TO ROLE ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA OLIST_DB.RAW TO ROLE ENGINEER;

GRANT USAGE ON SCHEMA OLIST_DB.STAGING TO ROLE ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA OLIST_DB.STAGING TO ROLE ENGINEER;

GRANT USAGE ON SCHEMA OLIST_DB.MARTS TO ROLE ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA OLIST_DB.MARTS TO ROLE ENGINEER;

GRANT USAGE ON SCHEMA OLIST_DB.MARTS TO ROLE ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA OLIST_DB.MARTS TO ROLE ANALYST;

GRANT USAGE ON SCHEMA OLIST_DB.MARTS TO ROLE REPORTER;
GRANT SELECT ON ALL TABLES IN SCHEMA OLIST_DB.MARTS TO ROLE REPORTER;

GRANT ROLE ENGINEER TO USER OLIST_USER;
GRANT ROLE ANALYST TO USER OLIST_USER;
GRANT ROLE REPORTER TO USER OLIST_USER;